// eslint-disable-next-line no-shadow
export enum FeeValidationError {
  FEE_CANNOT_BE_NEGATIVE,
  FEE_RATE_CANNOT_BE_NEGATIVE,
  FEE_TOO_HIGH,
  FEE_RATE_TOO_HIGH,
  INPUT_AMOUNT_MUST_BE_POSITIVE,
  INVALID_FEE,
  INVALID_FEE_RATE,
  INVALID_INPUT_AMOUNT,
}
